from sqlalchemy import CheckConstraint, Column, Integer, MetaData, String, Table, Text, UniqueConstraint


TABLE_NAMES = [
    "users", "audit_logs", "qa_conversations", "qa_messages", "agent_conversations", "agent_messages",
    "agent_runs", "local_agent_connectors", "debug_payloads", "files", "artifacts", "datasets",
    "dataset_files", "dataset_jobs", "app_kv", "agent_blueprints", "agent_blueprint_versions",
    "agent_blueprint_test_cases", "agent_blueprint_releases", "agent_blueprint_test_runs",
    "agent_blueprint_validation_results", "schema_migrations",
]


def _common_metadata(table: Table) -> Table:
    return table


def define_tables(metadata: MetaData) -> None:
    Table("users", metadata, Column("user_id", String, primary_key=True), Column("username", String, unique=True, nullable=False), Column("display_name", Text), Column("password_hash", Text, nullable=False), Column("role", String, nullable=False), Column("is_enabled", Integer, default=1), Column("auth_version", Integer, default=1), Column("created_at", Text), Column("updated_at", Text), Column("last_login_at", Text), Column("metadata_json", Text))
    Table("audit_logs", metadata, Column("audit_id", String, primary_key=True), Column("user_id", String), Column("username", String), Column("action", String, nullable=False), Column("resource_type", String), Column("resource_id", String), Column("detail_json", Text), Column("ip", String), Column("user_agent", Text), Column("created_at", Text))
    Table("qa_conversations", metadata, Column("conversation_id", String, primary_key=True), Column("user_id", String, nullable=False), Column("title", Text), Column("status", String), Column("is_archived", Integer, default=0), Column("created_at", Text), Column("updated_at", Text), Column("last_opened_at", Text), Column("metadata_json", Text))
    Table("qa_messages", metadata, Column("message_id", String, primary_key=True), Column("conversation_id", String, nullable=False), Column("user_id", String, nullable=False), Column("role", String, nullable=False), Column("content", Text), Column("status", String), Column("sources_json", Text), Column("warnings_json", Text), Column("error", Text), Column("created_at", Text), Column("updated_at", Text), Column("metadata_json", Text))
    Table("agent_conversations", metadata, Column("conversation_id", String, primary_key=True), Column("user_id", String, nullable=False), Column("title", Text), Column("type", String), Column("selected_agent_id", String), Column("agent_type", String), Column("latest_run_id", String), Column("status", String), Column("is_archived", Integer, default=0), Column("created_at", Text), Column("updated_at", Text), Column("last_opened_at", Text), Column("metadata_json", Text))
    Table("agent_messages", metadata, Column("message_id", String, primary_key=True), Column("conversation_id", String, nullable=False), Column("user_id", String, nullable=False), Column("role", String, nullable=False), Column("content", Text), Column("status", String), Column("run_id", String), Column("created_at", Text), Column("updated_at", Text), Column("metadata_json", Text))
    Table("agent_runs", metadata, Column("run_id", String, primary_key=True), Column("user_id", String, nullable=False), Column("conversation_id", String), Column("agent_id", String), Column("agent_type", String), Column("status", String), Column("mode", String), Column("input_json", Text), Column("workflow_options_json", Text), Column("result_json", Text), Column("error", Text), Column("artifacts_json", Text), Column("created_at", Text), Column("updated_at", Text), Column("started_at", Text), Column("completed_at", Text), Column("metadata_json", Text), Column("row_version", Integer, default=1))
    Table("local_agent_connectors", metadata, Column("connector_id", String, primary_key=True), Column("name", Text, nullable=False), Column("connector_type", String), Column("enabled", Integer, default=1), Column("base_url", Text), Column("command", Text), Column("timeout_seconds", Integer), Column("created_by", String), Column("created_at", Text), Column("updated_at", Text), Column("metadata_json", Text))
    Table("debug_payloads", metadata, Column("payload_id", String, primary_key=True), Column("user_id", String), Column("connector_id", String), Column("agent_id", String), Column("request_json", Text), Column("response_json", Text), Column("status", String), Column("created_at", Text), Column("updated_at", Text), Column("metadata_json", Text))
    Table("files", metadata, Column("file_id", String, primary_key=True), Column("user_id", String, nullable=False), Column("filename", Text), Column("storage_path", Text), Column("content_type", String), Column("size_bytes", Integer), Column("source", String), Column("created_at", Text), Column("updated_at", Text), Column("metadata_json", Text))
    Table("artifacts", metadata, Column("artifact_id", String, primary_key=True), Column("user_id", String, nullable=False), Column("run_id", String), Column("filename", Text), Column("storage_path", Text), Column("download_url", Text), Column("content_type", String), Column("size_bytes", Integer), Column("created_at", Text), Column("updated_at", Text), Column("metadata_json", Text), Column("storage_backend", String, default="local"), Column("object_key", Text), Column("original_filename", Text), Column("checksum", String))
    Table("datasets", metadata, Column("dataset_id", String, primary_key=True), Column("user_id", String, nullable=False), Column("name", Text), Column("description", Text), Column("source_filename", Text), Column("source_path", Text), Column("status", String), Column("row_count", Integer), Column("valid_row_count", Integer), Column("excluded_row_count", Integer), Column("columns_json", Text), Column("field_mapping_json", Text), Column("cleaning_rules_json", Text), Column("profile_json", Text), Column("metrics_json", Text), Column("created_at", Text), Column("updated_at", Text), Column("metadata_json", Text))
    Table("dataset_files", metadata, Column("file_id", String, primary_key=True), Column("dataset_id", String, nullable=False), Column("user_id", String, nullable=False), Column("file_type", String), Column("filename", Text), Column("storage_path", Text), Column("content_type", String), Column("size_bytes", Integer), Column("created_at", Text), Column("metadata_json", Text))
    Table("dataset_jobs", metadata, Column("job_id", String, primary_key=True), Column("dataset_id", String), Column("user_id", String), Column("job_type", String), Column("status", String), Column("input_json", Text), Column("result_json", Text), Column("error", Text), Column("created_at", Text), Column("updated_at", Text), Column("metadata_json", Text))
    Table("app_kv", metadata, Column("key", String, primary_key=True), Column("value_json", Text), Column("updated_at", Text))
    Table("agent_blueprints", metadata, Column("blueprint_id", String, primary_key=True), Column("agent_id", String), Column("name", Text, nullable=False), Column("display_name", Text, nullable=False), Column("description", Text), Column("category", String), Column("icon", String), Column("status", String, nullable=False), Column("current_version_id", String), Column("published_version_id", String), Column("created_by", String, nullable=False), Column("updated_by", String), Column("created_at", Text, nullable=False), Column("updated_at", Text, nullable=False), Column("metadata_json", Text), CheckConstraint("status IN ('draft','testing','published','disabled','deprecated')"))
    Table("agent_blueprint_versions", metadata, Column("version_id", String, primary_key=True), Column("blueprint_id", String, nullable=False), Column("version_number", Integer, nullable=False), Column("version_name", Text), Column("change_summary", Text), Column("input_schema_json", Text), Column("methodology_json", Text), Column("prompt_config_json", Text), Column("execution_config_json", Text), Column("output_schema_json", Text), Column("result_ui_config_json", Text), Column("acceptance_rules_json", Text), Column("created_by", String, nullable=False), Column("created_at", Text, nullable=False), Column("is_published", Integer, default=0), Column("parent_version_id", String), Column("metadata_json", Text), UniqueConstraint("blueprint_id", "version_number"))
    Table("agent_blueprint_test_cases", metadata, Column("test_case_id", String, primary_key=True), Column("blueprint_id", String, nullable=False), Column("version_id", String), Column("name", Text, nullable=False), Column("description", Text), Column("input_json", Text, nullable=False), Column("expected_status", String), Column("expected_result_rules_json", Text), Column("expected_artifacts_json", Text), Column("max_duration_seconds", Integer), Column("requires_connector", Integer, default=0), Column("is_enabled", Integer, default=1), Column("created_by", String, nullable=False), Column("created_at", Text, nullable=False), Column("updated_at", Text, nullable=False), Column("last_run_id", String), Column("last_result_json", Text), Column("metadata_json", Text))
    Table("agent_blueprint_releases", metadata, Column("release_id", String, primary_key=True), Column("blueprint_id", String, nullable=False), Column("version_id", String, nullable=False), Column("action", String, nullable=False), Column("from_version_id", String), Column("to_version_id", String), Column("operator_user_id", String, nullable=False), Column("note", Text), Column("created_at", Text, nullable=False), Column("metadata_json", Text), CheckConstraint("action IN ('publish','rollback','disable','enable','deprecate')"))
    Table("agent_blueprint_test_runs", metadata, Column("test_run_id", String, primary_key=True), Column("blueprint_id", String, nullable=False), Column("version_id", String, nullable=False), Column("test_case_id", String, nullable=False), Column("agent_run_id", String), Column("status", String, nullable=False), Column("expected_status", String), Column("actual_status", String), Column("started_at", Text, nullable=False), Column("completed_at", Text), Column("duration_ms", Integer), Column("result_summary_json", Text), Column("validation_result_json", Text), Column("missing_result_fields_json", Text), Column("missing_artifacts_json", Text), Column("error_message", Text), Column("created_by", String, nullable=False), Column("metadata_json", Text))
    Table("agent_blueprint_validation_results", metadata, Column("validation_id", String, primary_key=True), Column("blueprint_id", String, nullable=False), Column("version_id", String, nullable=False), Column("is_valid", Integer, nullable=False), Column("error_count", Integer, default=0), Column("warning_count", Integer, default=0), Column("errors_json", Text), Column("warnings_json", Text), Column("checked_at", Text, nullable=False), Column("checked_by", String, nullable=False), Column("validator_version", String), Column("metadata_json", Text))
    Table("schema_migrations", metadata, Column("version", String, primary_key=True), Column("applied_at", Text), Column("description", Text))
