export const queryKeys = {
  currentUser: ["current-user"] as const,
  runtimeHealth: ["runtime-health"] as const,
  storageHealth: ["storage-health"] as const,
  agentConversations: (params: { limit?: number; include_archived?: boolean } = {}) => [
    "agent-conversations",
    params.limit || 50,
    Boolean(params.include_archived),
  ] as const,
  qaConversations: (limit = 50) => ["qa-conversations", limit] as const,
  knowledgeStats: ["knowledge-stats"] as const,
  qaModelStatus: (includeLoadCheck = false) => ["qa-model-status", includeLoadCheck] as const,
  knowledgeDocuments: ["knowledge-documents"] as const,
  agentConnectors: ["agent-connectors"] as const,
  agentBlueprints: ["agent-blueprints"] as const,
  agentBlueprint: (blueprintId?: string | null) => ["agent-blueprint", blueprintId || ""] as const,
  agentBlueprintValidations: (blueprintId?: string | null) => ["agent-blueprint-validations", blueprintId || ""] as const,
  agentBlueprintTestRuns: (blueprintId?: string | null) => ["agent-blueprint-test-runs", blueprintId || ""] as const,
  agentBlueprintDiff: (blueprintId?: string | null, fromVersionId?: string | null, toVersionId?: string | null) => ["agent-blueprint-diff", blueprintId || "", fromVersionId || "", toVersionId || ""] as const,
  debugPayloads: (params: { limit?: number; agent_type?: string; status?: string } = {}) => [
    "debug-payloads",
    params.limit || 50,
    params.agent_type || "",
    params.status || "",
  ] as const,
  datasets: (params: { status?: string; limit?: number } = {}) => ["datasets", params.status || "", params.limit || 50] as const,
  uploadedFiles: (extensions = "xlsx,xls,csv", limit = 50) => ["uploaded-files", extensions, limit] as const,
  datasetMappingTemplates: ["dataset-mapping-templates"] as const,
  agentConfigs: ["agent-configs"] as const,
  skills: (agentType?: string) => ["skills", agentType || ""] as const,
  adminUsers: (params: { role?: string; enabled?: string; keyword?: string; limit?: number } = {}) => [
    "admin-users",
    params.role || "",
    params.enabled || "",
    params.keyword || "",
    params.limit || 100,
  ] as const,
};
